[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Christian Wander <chris.wander@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
